### ISSUE TITLE
Split yt-looper.js into modules

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#104]
This is just something to keep in mind, if codebase grows too big.
Each player should have a separate file etc.

```javascript
var ytPlayer = require('YouTubePlayer');
```

Refs.
- http://wiki.commonjs.org/wiki/Modules/1.1
- http://browserify.org/
- http://webpack.github.io

**Comment by sk4zuzu** [comment]
I think it is a must. I'll look into it. :rocket:

**Comment by lidel** [comment]
I dont have any preference, but I think we should pick a solution that is future-proof and compatible with ECMAScript 2015 (ES6) standard:
Ref. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by lidel** [comment]
Closing this, as it is duplicated by https://github.com/lidel/yt-looper/issues/48
