### ISSUE TITLE
new feature: html5 mp4 player for generic urls *.mp4 *.webm

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#115]
This seems reasonable and simple since we already use some `<video>` tags (#101).

For example we could try to make work something like that:
https://yt.aergia.eu/#v=https://vt.tumblr.com/tumblr_npa1dkYP1U1urdxm4.mp4&t=4s;5s

It is quite easy to set start and end of interval (at least in chrome), you can probably do it just like that:
https://vt.tumblr.com/tumblr_npa1dkYP1U1urdxm4.mp4#t=4,5

Catching video end event is also possible.

I'd like to spend some time on that if you don't mind.
My js bones are a bit rusty, but this is better than having leukemia right ?

\\:D/

**Comment by lidel** [comment]
Sounds good. Feel free to work on this. :+1: 

My 2 cents:
- `HTML5Player` should be used instead of `YouTubePlayer` if value of `v=` parameter starts with `http` and ends with `.mp4` or `.webm`
- Looped HTML5 player is implemented in `ImgurPlayer`.  You can reuse it as a boilerplate (while ignoring Imgur-specific code).

**Comment by sk4zuzu** [comment]
I have that weird itch on the back of my head... Shouldn't we detect generic video only by checking if it begins with 'https?://' ? Then it would be possible to paste `goo.gl` url there. For now it is impossible to have `&` inside url... It is kinda crippled so to speak. What do you think ? :frog:

**Comment by lidel** [comment]
I agree: check for `https?://` should be enough.
Feel free to create a PR that removes check for suffixes (`.mp4`, `.webm`).

Another idea: additionally, we could also check for `/` --  YouTube IDs do not contain this character (`[A-Za-z0-9_-]` only)
Relying on `/` detection would enable us to support URL IDs without protocol in the URL, for example: `#v=fqdn.com/video_file` (we should support both, with and without protocol).

**Comment by sk4zuzu** [comment]
Agreed. I will work on that.

**Comment by lidel** [comment]
:ok_hand:
