### ISSUE TITLE
Refunctoring

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#121]
Now that we know the app's business, @sk4zuzu suggested refactoring using functional approach. 
The library we chose is http://ramdajs.com

This ticket will track the progress and serve as a discussion platform.

Please include its URL ( #121) in commit messages, so that changes are displayed here.

**Comment by sk4zuzu** [comment]
Will do. For now I'm doing research on ramdajs. It has different design than underscore or lodash, so we will probably start using more function composition and monadic patterns rather than simple chaining, which btw isn't really functional programming. \\:D/

**Comment by sk4zuzu** [comment]
I don't think I'll be working on this project anymore \\:D/ and I don't know if this ramda-idea is really sound (unlikely). In the end if it is my call I'd drop it and do sth instead. \\:D/

**Comment by lidel** [comment]
I understand. Thank you for your contributions so far. :ok_hand: 

Closing this ticket: I don't have motivation to do full refactoring myself, especially now when we stabilized and have sane test suite. If anything, will just move to https://lodash.com at some point in future (successor of UnderscoreJS).

**Comment by sk4zuzu** [comment]
I  used `lodash` lately (might be older version) for one project and there was big difference in `_(<array>).*` handling. In `lodash` it seems to work just like `.chain().*.value()` so refactoring will be needed I guess.
