### ISSUE TITLE
Setting the speed

### ISSUE THREAD

**Issue by piotrKantor** [lidel/yt-looper#156]
It would be really nice if it was possible to setting speed of a video or playlist.

Some videos of conferences or tutorials have too much pauses or to little content to be watch in regular speed.

[This might be helpful](http://stackoverflow.com/questions/22604934/html5-increase-youtube-speed-2x-from-url )

**Comment by lidel** [comment]
Done. Refresh cache and give it a try: https://yt.aergia.eu/#v=h73bd9b5pPA&speed=1.5
