### ISSUE TITLE
Anti Screamers filter

### ISSUE THREAD

**Issue by piotrKantor** [lidel/yt-looper#171]
Some toggle volume normalization would be really nice.

**Comment by lidel** [comment]
Out of scope: YouTube player API  does not provide low level access to audio track, making it impossible to do any kind of analysis and normalization. We can only control volume.

You may want to do the normalization within your OS audio subsystem. 
It is quite easy under Linux with PulseAudio and LADSPA sink:

- https://github.com/gotbletu/shownotes/blob/master/pulseaudio-dynamic-range-compression.md
