### ISSUE TITLE
Clipping/Masking over gifs/videos

### ISSUE THREAD

**Issue by piotrKantor** [lidel/yt-looper#200]
It would be nice if there was possibility to clip/mask videos so that instead of whole video recipient of link could have seen(?) only an unmasked part.

For example, the mask is a drawn cat with big anime-style transparent eyes, and only those eyes "presents" some content(movie or gif).

It could by done by some z-index or whatever method is proper these days.

**Comment by lidel** [comment]
Sounds quite elaborate, but let's entertain the idea and list some assumptions:

- new global parameter `&overlay=<url>`  where `<url>` is URL to image 
- overlay  is displayed on top of `#box` / `#player` as divs with 
  `width:100%;height:100%;background:url(<url>) no-repeat center center fixed;background-size:cover;`    
  it should be universal enough to cover all player sizes
-  if the image is PNG/GIF alpha channel, then parts of underlying player are visible
- the overlay is static and always visible -- common to all playlist items

Is this what you had in mind?

**Comment by piotrKantor** [comment]
Yes, that would be exactly what I expected.

**Comment by lidel** [comment]
### Triage Decision

Won't be implemented.

### Rationale

Year later this idea seems like a book case of [Rube-Goldberg machine](https://en.wikipedia.org/wiki/Rube_Goldberg_machine).

Closing this due to the lack of interest and limited usefulness of such feature.
