### ISSUE TITLE
Find a problem solved by JSON Web Token (JWT) 

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#21]
I just really want to use format described at http://jwt.io for something, but I don't see any use case :'C
Perhaps we could have a button which would 'lock' current set of videos into digitally signed JWT?
![2014-10-01-202836_1009x593_scrot](https://cloud.githubusercontent.com/assets/157609/4480612/c89b4412-4998-11e4-915c-700b943b34c4.png)

Any other ideas?

**Comment by lidel** [comment]
Idea: signed URLs should be used:
- as input for URL shortener
- in iframe embedd code

**Comment by lidel** [comment]
JS implementation is a part of a bigger library (https://kjur.github.io/jsrsasign/) and weights 78,74 KB (80 628 bytes).

Too big for this app, closing.

**Comment by sk4zuzu** [comment]
:'C
