### ISSUE TITLE
Start time and end time not workin on Fx with media.autoplay.enable flag set to false

### ISSUE THREAD

**Issue by piotrKantor** [lidel/yt-looper#277]
On Fx 55.0.2 wit media.autoplay.enable flag set to false start time is ignored
https://yt.aergia.eu/#v=7uBNCN6v_gk&v=24s;1m52s

but native YT link with start time works just fine
https://youtu.be/7uBNCN6v_gk?t=30s

**Comment by lidel** [comment]
Your links has a typo (`&v=` instead of `&t=`). 
This one works fine: https://yt.aergia.eu/#v=7uBNCN6v_gk&t=24s;1m52s

🌵
