### ISSUE TITLE
Add url variable to start video in defined quality (eg. &q=460p, &q=720p etc.)

### ISSUE THREAD

**Issue by tanatospl** [lidel/yt-looper#31]

**Comment by lidel** [comment]
Should be trivial: `&quality=` and https://developers.google.com/youtube/iframe_api_reference#Playback_quality

**Comment by lidel** [comment]
Done. To cap video quality at preferred level (global setting) append:
```
&quality=<level>
```
Current list of available levels can be found in [YouTube Player API Reference](https://developers.google.com/youtube/iframe_api_reference#Playback_quality).

For example:
https://yt.aergia.eu/#v=ZuHZSbPJhaY&t=1h;1h5s&quality=small
https://yt.aergia.eu/#v=ZuHZSbPJhaY&t=1h;1h5s&quality=hd720
