### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#43]
This is some crazy idea. I think it would be nice to have possibility to interleave some videos and images (jpg/png/gif/gifv) to create better extraordinary stories! :pig: :hammer:

Basic url element could look like: [#:]i=H9d56aW.jpg:t=5s, where t is the duration of image exposition
(in the absence of t we could provide some sensible default).

:rocket:

**Comment by lidel** [comment]
`ImgurPlayer` is already here, so I'll close this ticket.
Enhancements to this basic functionality will be tracked under [UX-images](https://github.com/lidel/yt-looper/milestones/UX-images) milestone.
