### ISSUE TITLE
Migrate codebase to ECMAScript 6

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#48]
>  ECMAScript 6 (ES6) still sounds like something from a far-away future. After all, it will only become a standard by mid 2015. However, its features are continually appearing in browsers and there are compilers that translate ES6 code to ES5 code. The latter is already a compelling solution, because the ECMAScript 6 feature set is already frozen. 
-- [Using ECMAScript 6 today ](http://www.2ality.com/2014/08/es6-today.html)

> Today I used a Grunt task called grunt-traceur by Aaron Frost to author code in ES6 (maximally minimal classes, modules, rest params, spread operators) and transpile back to ES5 as a build-step. It felt fantastic and the final product now runs in all modern browsers. 
-- [Author In ES6, Transpile To ES5 As A Build-step: A Workflow For Grunt](http://addyosmani.com/blog/author-in-es6-transpile-to-es5-as-a-build-step-a-workflow-for-grunt)

More about ECMAScript 6: http://git.io/es6features

**Comment by sk4zuzu** [comment]
ECMAScript 6 looks fantastic! ...especially generators, arrows and tail calls.
What about rewriting everything in functional style using recurrence, monads and applicative functors ? :trollface: :rocket: ?

**Comment by lidel** [comment]
I'm game, as long as there are no regressions and code is easier to maintain :+1:  :trollface: 

But before we do anything, we need to create some tests for Editor to avoid any regressions caused by migration.

This may be hard to test via headless test suite. Perhaps we should have a second set of tests that run in real browser: TravisCI supports it, I do it for [ipfs-firefox-addon](https://travis-ci.org/lidel/ipfs-firefox-addon). 

I'll look into it this weekend.

**Comment by lidel** [comment]
Closing this.

A year later the test harness is present and [a lot ES6 features are supported by both Firefox and Chrome](https://kangax.github.io/compat-table/es6/).  I don't have motivation to refactor old code, but new features can use ES6 features.

**Comment by sk4zuzu** [comment]
:)
