### ISSUE TITLE
“Restricted from playback on certain sites” error for some videos

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#6]
For some reason 
http://yt.aergia.eu/#v=6fGdZh_eg9U
is blocked but the same video at 
http://www.infinitelooper.com/?v=6fGdZh_eg9Ua
works fine. 

Investigate: Would it work with any .com domain, or is there a geoip lookup behind the scenes?
Perhaps we could detect 'not available' message and redirect user to alternative domain.

**Comment by aburke20** [comment]
Had this issue for what seems forever, can't believe the fix was this simple !
