### ISSUE TITLE
Support for IE 6/7/8 

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#67]
> jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8.

In spare moment we should find a machine with old IE, switch jquery to 1.x and see if it works without any other change. If so, I think it would not cost us any work to support the retarded browser.

**Comment by sk4zuzu** [comment]
I agree, it is a good thing not to support IE at all... xD

**Comment by lidel** [comment]
Ok, this will not work: we are using IFrame API for YouTube and:

> The end user must be using a browser that supports the HTML5 `postMessage` feature. Most modern browsers support `postMessage`, though Internet Explorer 7 does not support it.

Nvm then ;-)

**Comment by sk4zuzu** [comment]
Everybody has moments of weakness... ;D
