### ISSUE TITLE
The deprecation of the YouTube JavaScript Player API

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#73]
> The deprecation of the YouTube JavaScript Player API was announced on January 27, 2015. YouTube Flash <object> embeds have also been deprecated. See the deprecation policy for more information. Please migrate your applications to the IFrame API, which can intelligently use whichever embedded player – HTML (<video>) or Flash (<object>) – the client supports.

Source: https://developers.google.com/youtube/js_api_reference

**Comment by lidel** [comment]
Good thing we already use IFrame API :+1:

**Comment by sk4zuzu** [comment]
\e/
