### ISSUE TITLE
Shuffle feature rewrite question

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#74]
When I was implementing the "editor" feature I encountered problem with shuffle. Currently shuffle works on the internal playlist structure only (changing it). So basically you see some interval ordering in URL or editor (those two are the same) but enabling shuffle does not change that ordering (so I had to disable shuffle in editor...). I think the new shuffle should be enabled manually via user click and should modify URL (via hash change) or at least modify URL. Then it would fit nicer to the "editor" concept and it would make code more explicit and simpler. What do you think ?

**Comment by lidel** [comment]
Please check https://github.com/lidel/yt-looper/commit/c27c45bebd0ba14eb7be82e115b2ffee6dc5a73b I just pushed it. 

With this change shuffle is not statically generated,
but is calculated on the fly before playing next item.

Thanks to this, it can coexist with editor
which displays items in the order from URL.

**Comment by sk4zuzu** [comment]
Superb! checking... :)

**Comment by sk4zuzu** [comment]
OK, I'm totally fine with that (http://goo.gl/29ltXJ) but it isn't exactly shuffle, right ? ;)
Maybe we should change the name (http://goo.gl/sYIIDM) to "random" ? ;)

**Comment by lidel** [comment]
Yes, `&random` makes more sense here. I'll rename it shortly.

**Comment by sk4zuzu** [comment]
Looks solid :+1:
