### ISSUE TITLE
Random does not work in chrome on aergia.eu (wut?)

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#75]
After #74 has been closed I think there is a bug :)

1. random does not work on aergia.eu in my chrome (Version 38.0.2125.101 (64-bit))
2. random does work on my local dev server in chrome (http://goo.gl/704HUd)
3. random does work in firefox without problems

4. basically when I do some clicks on "random" nothing happens :/
5. adding &random to the URL does nothing
6. adding &shuffle works, but there is no change in the UI
7. removing browser cache does not halp
8. I don't see any error logs

Please do some checks, I'll try to investigate this tomorrow :)

**Comment by sk4zuzu** [comment]
OK it seems to work now after few hours of sleep :+1: .
Maybe I was hallucinating, we will never know... xD
Could this be some kind of CDN problem ?

**Comment by lidel** [comment]
Yes, it is possible that I updated production but forgot to purge Cloudflare's cache, so it returned old version of `index.html` and/or `yt-looper.js`. :crying_cat_face: 

My apologies!

**Comment by sk4zuzu** [comment]
there there
