### ISSUE TITLE
Image without &t= should be displayed indefinitely

### ISSUE THREAD

**Issue by lidel** [lidel/yt-looper#80]
Current behaviour of `ImgurPlayer` is to assume `t=3s` as a default. 
Removing 3s default would enable yt-looper to serve as a simple image gallery with <kbd>j</kbd> and <kbd>k</kbd> keys used for navigation.

**Comment by sk4zuzu** [comment]
Nice idea ! We get some additional functionality for free, then still we can use "&t=" ! :+1: :rocket:
