### ISSUE TITLE
Editor URL link button

### ISSUE THREAD

**Issue by sp3json** [lidel/yt-looper#84]
After clicking "show URL button" on one of the items of playlist, you can't view/click another

**Comment by lidel** [comment]
Are you using Firefox too?

I tried to edit one of entries in sample playlist and indeed it gets stuck under Firefox: 
field with URL does not hide after clicking away nor kitting <kbd>Enter</kbd> or <kbd>Esc</kbd>:

> ![2015-04-14 11_30_32-analog sheep - i miss my amiga 500 music video](https://cloud.githubusercontent.com/assets/157609/7134089/e84245fa-e299-11e4-8f00-90f283eb0800.png)

It may be related to z-index, will investigate later.

**Comment by lidel** [comment]
This should be fixed by https://github.com/lidel/yt-looper/commit/c63782fabcf42dc291be6635bf91d7e859f5488a.

**Comment by sp3json** [comment]
98% is fixed :+1: ...
If U click URL Button (UB) this shows a URL box - nice everything is OK, but if U click anywhere URL box not hiding. But as U press the URL and then somewhere else (or ESC) then box disappears.

sorry for the poor logic in speech :)

**Comment by lidel** [comment]
Good catch! I removed hiding  box on `focusout` in https://github.com/lidel/yt-looper/commit/512c135cbc57a1d8046bfa4180001694e14f9b29. 

Please refresh and check again: 
Now it should not disappear on clicking outside the box.
Clicking on different Edit button or clicking inside the box and hitting <kbd>Enter</kbd> is required to save changes.
