### ISSUE TITLE
Scroll solution for editor window

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#88]
Currently (editor is still p-o-c) there is no scroll bar for editor window. That means if there are more too many intervals, user will not able to see all of them. My initial idea was not to create scroll bar but rather two buttons: upper button for scrolling "up" and lower button for scrolling "down". Clicking a button would rewind the list just like pgup or pgdown does in text editors. What do you think ? (:rocket: ?)

**Comment by lidel** [comment]
Buttons may be a solution, but it requires custom widget that takes space.
Perhaps we could implement thin scrollbar in OSX style somehow? 

Something like this, or thinner (and it would fade out when not used):
> ![](http://danareilly.github.io/prework/cl/Graphics/terminal_scroll_scrollback.gif)

I guess we could also add keybinding for <kbd>PgUp</kbd>, <kbd>PgDown</kbd> 
and mouse scroll too. Scrollbar is the first step :+1: .

Anyway, we can use this playlist for testing: 
http://yt.aergia.eu/#list=PL358E88252C590308 (it has 55 videos)

**Comment by sk4zuzu** [comment]
I totally agree (https://yt.aergia.eu/#v=Tt-tG6ufH90&t=22s;25s) if we keep that scroll bar really thin! xD :+1:

**Comment by lidel** [comment]
I think we could use this:
http://manos.malihu.gr/jquery-custom-content-scroller/

The thin one from demo page  looks promising:
http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html

**Comment by sk4zuzu** [comment]
very nice :+1: :roller_coaster:

**Comment by lidel** [comment]
http://yt.aergia.eu/#list=PL358E88252C590308&index=55
Done!  Enjoy scrollbar! :sparkles: :rocket: :rainbow:

**Comment by sk4zuzu** [comment]
:bikini: :dress: :high_heel: :lipstick: :kiss: :tractor:
