### ISSUE TITLE
Shortened links aggregation ?

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#92]
Assume we have two playlists with multiple videos and we want to join them easily.

(Of course we could copy over all intervals together, but this is trivial...)

What about providing shortened forms to yt-looper (goo.gl ids), then comes some magic blah blah and we have both list merged together with full playlist in editor ?

:trolleybus: :neckbeard:

**Comment by sk4zuzu** [comment]
Maybe we could revive #21 somehow along with this idea ? :sparkles:

**Comment by lidel** [comment]
How about syntax: `&expand=<short_link1>+<short_link2` ?

URL normalizer would evaluate short links and simply replace

    &expand=http://goo.gl/ycH3Px+http://goo.gl/LKbVEc

with 

    &v=ZuHZSbPJhaY&t=1h1s;1h4s&v=lWqJTKdznaM&t=58;68

**Comment by sk4zuzu** [comment]
what about: #http://goo.gl/ycH3Px&http://goo.gl/LKbVEc ?

This wouldn't limit us in any way! We could switch to different url shortener without any changes in aggregation code.

:neckbeard:

**Comment by lidel** [comment]
I am okay with `#http://goo.gl/ycH3Px&http://goo.gl/LKbVEc`, it is short and makes sense (replace short url with intervals it represents).

Normalizer will simply look for `http://goo.gl/` before currently existing rules, so there will not be any issues.

**Comment by lidel** [comment]
Voila! :rocket: 
https://yt.aergia.eu/#http://goo.gl/ycH3Px&http://goo.gl/LKbVEc
