### ISSUE TITLE
Keyboard shortcuts for controling audio volume in hidden mode

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/yt-looper#93]
I find it annoying: unhide player, hide editor, change volume, hide player, unhide editor. :anguished: 

Simple +/- would be nice... :+1: 

:sunglasses:

**Comment by lidel** [comment]
:+1:

**Comment by lidel** [comment]
Done.

Volume Down: <kbd>-</kbd> or <kbd>_</kbd>
Volume Up: <kbd>+</kbd> or <kbd>=</kbd>
